
name: Build and Publish

on:
  workflow_run:
    workflows: ["Test"]
    branches: ["master"]
    types: 
      - completed

jobs:
   build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install and build
        run: |
          yarn install
          yarn build
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: update_dotenv_build_artifacts
          path: |
            dist/
            es/
            lib/

   publish:
    runs-on: ubuntu-latest
    needs: [build]

    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: update_dotenv_build_artifacts    
      - run: yarn publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
